@protocol = http
@host = localhost
@port = 5004
@graphql_edp = {{protocol}}://{{host}}:{{port}}/graphql

###

POST {{graphql_edp}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query GetAllTopics {
    tracks {
        totalCount
        pageInfo {
            hasNextPage
            hasPreviousPage
        }
        nodes {
            id
            name
            sessions {
                id
                title
            }
        }
    }
}

###

POST {{graphql_edp}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query GetAllSessions {
    sessions {
        totalCount
        pageInfo {
            hasNextPage
            hasPreviousPage
        }
        nodes {
            id
            title
            abstract
            startTime
            endTime
            duration
            track {
                id
                name
            }
            speakers {
                id
                name
            }
            attendees {
                id
                username
            }
        }
    }
}

###

POST {{graphql_edp}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query GetAllSpeakers {
    speakers {
        totalCount
        pageInfo {
            hasNextPage
            hasPreviousPage
        }
        nodes {
            id
            name
            bio
            website
            sessions {
                id
                title
            }
        }
    }
}

###

POST {{graphql_edp}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query GetAllAttendees {
    attendees {
        totalCount
        pageInfo {
            hasNextPage
            hasPreviousPage
        }
        nodes {
            id
            username
            lastname
            firstname
            email
            sessions {
                id
                title
            }
        }
    }
}
