POST http://localhost:5004/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query GetOneRecord {
    attendee(id: "QXR0ZW5kZWUKaTE=") {
        id
        username
        lastname
        firstname
        email
        sessions {
            id
            title
        }
    }
    session(id: "U2Vzc2lvbgppMQ==") {
        id
        title
        abstract
        startTime
        endTime
        duration
        track {
            id
            name
        }
        speakers {
            id
            name
        }
        attendees {
            id
            username
        }
    }
    speaker(id: "U3BlYWtlcgppMQ==") {
        id
        name
        bio
        website
        sessions {
            id
            title
        }
    }
    track(id: "VHJhY2sKaTE=") {
        id
        name
        sessions {
            id
            title
        }
    }
}
