@protocol = http
@host = localhost
@port = 5004
@graphql_edp = {{protocol}}://{{host}}:{{port}}/graphql

###

POST {{graphql_edp}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

mutation PostSessionSpeaker {
    addSessionSpeaker(
        input: {
            sessionId: "U2Vzc2lvbgppMQ==",
            speakerId: "U3BlYWtlcgppMQ=="
        }
    ) {
        sessionSpeakerErrors {
            type
            code
            description
        }
    }
}

###

POST {{graphql_edp}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

mutation PostSessionAttendee {
    addSessionAttendee(
        input: {
            sessionId: "U2Vzc2lvbgppMQ==",
            attendeeId: "QXR0ZW5kZWUKaTE="
        }
    ) {
        sessionAttendeeErrors {
            type
            code
            description
        }
    }
}
