@protocol = http
@host = localhost
@port = 5004
@graphql_edp = {{protocol}}://{{host}}:{{port}}/graphql

###

POST {{graphql_edp}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

mutation PostTrack {
    addTrack(input: { name: "GraphQL" }) {
        track {
            id
            name
        }
        trackErrors {
            type
            code
            description
        }
    }
}

###

POST {{graphql_edp}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

mutation PostSession {
    addSession(
        input: {
            title: "Welcome to GraphQL"
            abstract: "Getting started with using GraphQL"
            startTime: "2024-01-01 08:00:00"
            endTime: "2024-01-01 10:00:00"
            trackId: 1
        }
    ) {
        session {
            id
            title
        }
        sessionErrors {
            type
            code
            description
        }
    }
}

###

POST {{graphql_edp}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

mutation PostSpeaker {
    addSpeaker(
        input: {
            bio: "Biography",
            name: "Jane Doe",
            website: null
        }
    ) {
        speaker {
            id
            name
        }
        speakerErrors {
            type
            code
            description
        }
    }
}

###

POST {{graphql_edp}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

mutation PostAttendee {
    addAttendee(
        input: {
            firstname: "John"
            lastname: "Doe"
            username: "john.doe"
            email: "john.doe@email.com"
        }
    ) {
        attendee {
            id
            username
        }
        attendeeErrors {
            type
            code
            description
        }
    }
}
