version: '3'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    volumes:
      - ../..:/workspaces:cached
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:postgres
    # Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
    #user: root
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  postgres:
    image: postgres:16 # TODO: Update with postgres version
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: GraphQL
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
    restart: unless-stopped

volumes:
  postgres-data:
