@protocol = http
@host = localhost
@port = 5002
@graphql_edp = {{protocol}}://{{host}}:{{port}}/graphql

###

POST {{graphql_edp}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query GetFilm {
    filmById(id: "RmlsbQppMg==") {
        id
        title
        characters {
            id
            name
        }
    }
}

###

POST {{graphql_edp}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query GetPlanet {
    planetById(id: "UGxhbmV0Cmk4") {
        id
        name
        residents {
            id
            name
        }
    }
}

###

POST {{graphql_edp}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query GetSpecies {
    speciesById(id: "U3BlY2llcwppOQ==") {
        id
        name
        people {
            id
            name
        }
    }
}

###

POST {{graphql_edp}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query GetCharacter {
    characterById(id: "Q2hhcmFjdGVyCmkx") {
        id
        name
        homeworld {
            id
            name
        }
        films {
            id
            title
        }
    }
}

###

POST {{graphql_edp}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query GetStarship {
    starshipById(id: "U3RhcnNoaXAKaTEy") {
        id
        name
        pilots {
            id
            name
        }
    }
}

###

POST {{graphql_edp}} HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query GetVehicle {
    vehicleById(id: "VmVoaWNsZQppMTQ=") {
        id
        name
        pilots {
            id
            name
        }
    }
}
